### ISSUE TITLE
Content Related Issues

### ISSUE THREAD

**Issue by dwij2812** [technocrats-robotics/technocrats-robotics.github.io#2]
Hey,

Please change the content as it might be objectionable. Also if possible keep it in private until development is complete.

https://github.com/technocrats-robotics/technocrats-robotics.github.io/blob/7e2b3d1aa537b6e2a1c3e59dbd3224b6e447b9e2/index.html#L53

**Comment by kunal768** [comment]
Thanks @dwij2812 the issue is resolved!
